version: 2
updates:
- package-ecosystem: "npm"
  directory: "/frontend"
  schedule:
    interval: "daily"
    open-pull-requests-limit: 3
  reviewers:
  - deissh
  assignees:
  - deissh
  labels:
  - dependencies
  - area/ayako
- package-ecosystem: gomod
  directory: "/ayako"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 3
  reviewers:
  - deissh
  assignees:
  - deissh
  labels:
  - dependencies
  - area/ayako
